### PR TITLE
Add support for Java runtime including environment variable and the tracing layer

### PR DESCRIPTION
**Pull request by drobakowski**
### What does this PR do?

Based on the #238 from @lizapressman, I've also added the necessary environment variables and the tracing layer for Java.

### Motivation

Direct support for Java

### Testing Guidelines

We're testing this in our environment, so far everything looks good.

### Additional Notes

See #238 for more details

### Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

**Comment by tianchu** [comment]
@drobakowski Thanks for submitting the PR! I believe we are already working on this https://github.com/DataDog/serverless-plugin-datadog/pull/238. cc: @lizapressman

**Comment by tianchu** [comment]
BTW, in a few months, there will be no code changes required for monitoring java functions, and the plugin will be able to automate all the changes required. Stay tuned.

**Comment by drobakowski** [comment]
> @drobakowski Thanks for submitting the PR! I believe we are already working on this #238. cc: @lizapressman

Hi @tianchu, thanks for the quick response, this PR is actually an addition to #238 and the fork points to @lizapressman feature branch.

**Review by lizapressman — COMMENTED** [review]
Hello, sorry about closing this. I merged in my branch and it automatically closed your PR. You can go ahead and reopen against master and I will try to take a look as soon as I can

**Comment by drobakowski** [comment]
> Hello, sorry about closing this. I merged in my branch and it automatically closed your PR. You can go ahead and reopen against master and I will try to take a look as soon as I can

Hi @lizapressman, no problem. I've created two new PRs #247 #248, could you be so kind and look at it?

**Pull request closed without merging**
