### PR TITLE
Handle empty stepFunctions object

### PR DESCRIPTION
**Pull request by martinamps**
### What does this PR do?

Handles `undefined` in the case of no step functions to recommend instrumentation to

### Motivation

```
Error raise when inspecting if there are any uninstrumented Step Functions state machines. Error: TypeError: Cannot read properties of undefined (reading 'stateMachines')
```

### Types of changes

- [ x ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

**Comment by kimi-p** [comment]
Hey @martinamps, I think the error only happens if any of these two env vars is set `config.enableStepFunctionsTracing || config.subscribeToStepFunctionLogs`. If anyone set one of these flag but not have any Step Functions to instrument, this error message is meant to be more explicit and help the user of datadog-plugin to identify if they are missing anything. 

Could you elaborate why you are seeing this error and what is your expected behavior? Thank you!

**Comment by Valentyn103** [comment]
> Hey @martinamps, I think the error only happens if any of these two env vars is set `config.enableStepFunctionsTracing || config.subscribeToStepFunctionLogs`. If anyone set one of these flag but not have any Step Functions to instrument, this error message is meant to be more explicit and help the user of datadog-plugin to identify if they are missing anything.
> 
> Could you elaborate why you are seeing this error and what is your expected behavior? Thank you!


I have the same error in all serverless repositories, even though we are not using any of the configs that you mentioned.
`datadog: {
  flushMetricsToLogs: true,
  apiKey: '#########',
  addLayers: true,
  logLevel: 'info',
  enableXrayTracing: true,
  enableDDTracing: true,
  subscribeToAccessLogs: true,
  forwarderArn: '############',
  enableTags: true,
  injectLogContext: true,
  monitors: [{
    high_error_rate: true
  }, {
    timeout: true
  }, {
    out_of_memory: true
  }, {
    high_iterator_age: true
  }, {
    high_cold_start_rate: true
  }, {
    high_throttles: true
  }, {
    increased_cost: true
  }]
}`
**_Error raise when inspecting if there are any uninstrumented Step Functions state machines. Error: TypeError: Cannot read properties of undefined (reading 'stateMachines')_**

**Comment by kimi-p** [comment]
I see what you are saying now. I will approve and deploy this PR once our internal code freeze is lifted around early December. I have logged a ticket internally for me as a reminder. Please also feel free to at me after 12/10 in case I forgot. Thank you both for raising this issue and have this PR!

**Comment by kimi-p** [comment]
Going to close and reopen to trigger tests to be run again.

**Comment by kimi-p** [comment]
Integration test failed because of https://github.com/serverless/serverless/issues/12273

**Comment by kimi-p** [comment]
@Valentyn103 @martinamps Could you try with the latest release. The change is released. Sorry for the wait. Please open an issue if the message still persist. Thank you!

**Pull request closed without merging**
