### PR TITLE
Search monitor patch

### PR DESCRIPTION
**Pull request by johnbuildsthings**
### What does this PR do?
This pr adds pagination to the seachMonitors method.

### Motivation

We encountered an error where a serverless stack with 33 monitors would always return a 400 error while deploying monitors unless we first manually deleted all monitors associated with the stack.  Upon investigation I found that the searchMonitors method only fetches 30 monitors (the page size default for the search api), thus ensuring that there will always be 3 monitors that "exist" but are not part of the [serverlessMonitorIdByMonitorId](https://github.com/DataDog/serverless-plugin-datadog/blob/master/src/monitors.ts#L163) map.  DD will attempt to create instead of update these monitors resulting in a 400 error..

### Testing Guidelines

I added an additional test case which will return metadata stating that more than 1 page of monitors exists, this will trigger the searchMonitors method to iterate until it retrieves all the monitors.  No existing monitors are failing. I updated one of the existing test cases to return and array of monitors instead of a monitor object, this is what's expected base on reading the code and experiments with the api.

### Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [x] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

**Comment by sfirrin** [comment]
Thanks a lot for this @johnbuildsthings. Code looks good to me

The branch is failing the linter check, I think that should be fixed by running `prettier . write`

It's failing the integration test because the GH action doesn't get environment variables with community PRs, I'm going to run them in a duplicate testing branch

**Comment by sfirrin** [comment]
Integration tests pass https://github.com/DataDog/serverless-plugin-datadog/actions/runs/6643218659/job/18049787998, just need the lint and this should be ready

**Comment by johnbuildsthings** [comment]
@sfirrin I fixed the lint errors.  Let me know if there is more that I need to do to keep this moving?

**Review by sfirrin — APPROVED** [review]

**Comment by sfirrin** [comment]
That should be all @johnbuildsthings, thanks again for the contribution!

Merged just now and will release a new version with this today

**Comment by sfirrin** [comment]
Released in https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.49.0

Thanks @johnbuildsthings!

**Pull request merged**
