### PR TITLE
chore: Fix npm publish GitHub Action

### PR DESCRIPTION
**Pull request by lym953**
### Motivation
The GitHub Action added in https://github.com/DataDog/serverless-plugin-datadog/pull/540 failed to publish the npm package on release event. [GitHub Action log](https://github.com/DataDog/serverless-plugin-datadog/actions/runs/11960303068/job/33344004054) says
> error No token found and can't prompt for login when running with --non-interactive.

### What does this PR do?

Change the way to set npm publish token, following this discussion:
https://github.com/actions/setup-node/issues/81#issuecomment-623018474

#### Steps
1. Add this to `publish.yml`
```diff
on:
  release:
    types: [created]
+ push:
```
2. Push the commit

#### Result
The previous error is gone, and a new error appears:
> Couldn't publish package: "https://registry.npmjs.org/serverless-plugin-datadog: You cannot publish over the previously published versions: 5.74.0."

I think we can assume it's a success.

[GitHub Action log](https://github.com/DataDog/serverless-plugin-datadog/actions/runs/11960802481/job/33345624991)

### Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

**Review by purple4reina — APPROVED** [review]

**Review by purple4reina — CHANGES_REQUESTED** [review]
Hmm, actually on second thought, I feel a bit uneasy about writing a secret to disk like this. Can we add a step that will remove the npmrc file? Make sure it executes on success and failure?

**Comment by lym953** [comment]
@purple4reina I changed to another approach mentioned in another comment, which looks more secure.

**Review by purple4reina — APPROVED** [review]
love it

**Pull request merged**
